# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f82f4e11fb55723db1fead6807a03f94586bde9558a8c93506a328970a5086fe9096caaa36d8b1ce9b5de7d6baa84fd0f75b02af76cfb29764afeebe8072bb

test:
  secret_key_base: 97dee4413df387fa816f9f3ca46ea91f4bc50e8773b0e185a1c3d4bbbf1e07e35047cd5b75f2b450106b3535b5ff1f552235d4b3b02335f69d87e5bfea17492e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
